### ISSUE TITLE
ICommand and IDomain event don't have AggregateId

### ISSUE THREAD

**Issue by eswann** [ircnelson/enjoy.cqrs#45]
Hey @ircnelson 
Question on ICommand and IDomainEvent.  I understand that these are marker interfaces, but since any command or domain event must reference an aggregate, why don't these specify an AggregateId getter?

**Comment by ircnelson** [comment]
I wanted make this abstractions for marker only and free for framework consumer developer to build your implementation without mandatory properties.

If they wants use CQRS without Event Sourcing concept they can be do it. In this case, the aggregateId is unecessary.
