### ISSUE TITLE
Projection de-/serialization inconsistent with MongoDB package

### ISSUE THREAD

**Issue by joakimjm** [ircnelson/enjoy.cqrs#52]
When serializing projection entries, the `Session` class uses the `IProjectionSerializer` implemented by your `ProjectionSerializer` to serialize, which in turn uses the `ITextSerializer`. I've used your suggested `JsonSerializer` as my implementation of the `ITextSerializer` - that all works fine. However the `MongoProjectionRepository` news up a `BsonTextSerializer` when deserializing which then fails with a `FormatException`.

> System.FormatException: Element 'createdTime' does not match any field or property of class BCI.Prototype.Domain.Projections.TerminalProjection.
>    at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
>    at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
>    at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
>    at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer serializer, BsonDeserializationContext context)
>    at MongoDB.Bson.Serialization.BsonSerializer.Deserialize(BsonDocument document, Type nominalType, Action`1 configurator)
>    at EnjoyCQRS.EventStore.MongoDB.MongoProjectionRepository.<QuerySingleResult>d__16.MoveNext()

**Comment by ircnelson** [comment]
@joakimjm I have problems with MongoDB Driver BsonSerialization when properties classes is only getter.
i.e.: `public DateTime CreatedTime { get; }` it fails, and `public DateTime CreatedTime { get; private set; }` probably works.

Check this...

**Comment by joakimjm** [comment]
I fixed it by using the BsonSerializer in the ProjectionSerializer. Now the projections get deserialized using the same type that serializes them.

Projections just doesn't work out of the box using the default outline described in the [wiki](https://github.com/ircnelson/enjoy.cqrs/wiki).
